5.32.0
elementor/elementor-icons pull request #119
Opened 2024-10-09 19:02 UTC by nuritsha

2024-10-09 19:42 UTC, louiswol94 commented
@nuritsha Please see:
Step 1: https://github.com/elementor/elementor-icons/pull/112/files
Step 2: https://github.com/elementor/elementor-icons/pull/113/files

2024-10-09 19:42 UTC, louiswol94 requested changes
See comment

2024-10-10 10:38 UTC, arielk approved these changes

2024-10-10 11:05 UTC, louiswol94 approved these changes

2024-10-10 11:23 UTC, merged