Added new eicons for Elementor 3.1.0, including replacing responsive …
elementor/elementor-icons pull request #55
Opened 2021-01-13 09:09 UTC by udidol

…device icons - Updated E-Icons to v5.10.0.

2021-01-14 14:51 UTC, kobizz requested changes
Make sure that `.eot` and `.ttf` files are included

2021-01-14 14:51 UTC, kobizz commented on css/elementor-icons.css
> +.eicon-pro:before {
We already have `.eicon-pro-icon` that looks the same

2021-01-14 14:51 UTC, kobizz commented on scss/_icons.scss
Make sure all icons code are consecutive

2021-01-17 14:41 UTC, kobizz requested changes
What happened to `.eot` and `.ttf` files?

2021-01-17 14:41 UTC, kobizz commented on scss/_icons.scss
> +.eicon-device-base:before { content: '\e97e'; }
This icon has to be removed

2021-01-17 14:41 UTC, kobizz commented on index.html
> +        /* You can be more comfortable with increased eicons size */
?

2021-01-17 17:20 UTC, udidol commented on css/elementor-icons.css
> +.eicon-default_desktop:before {
removed.

2021-01-17 17:20 UTC, udidol commented on scss/_icons.scss
> +.eicon-device-base:before { content: '\e97e'; }
Done.

2021-01-17 17:20 UTC, udidol commented on index.html
> +        /* You can be more comfortable with increased eicons size */
Fixed.

2021-01-18 10:17 UTC, kobizz approved these changes

2021-01-18 10:17 UTC, merged